name: Check websites

on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  check_websites:
    runs-on: ubuntu-22.04

    steps:
    - name: Check websites
      uses: actions/checkout@v3
      with:
        ref: main
      id: checkout

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install requests
    - name: Check websites
      env:
        PYTHONPATH: ${{ steps.checkout.workspace }}
      run: |
        source env/bin/activate
        python ${{ steps.checkout.workspace }}/blogs-ciberseguridad/check_websites.py
        
