name: Check websites

on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  check_websites:
    runs-on: ubuntu-20.04

    steps:
    - name: Check websites
      uses: actions/checkout@v3
      with:
        ref: main
      id: checkout

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install requests

    - name: Check websites
      env:
        WEBSITE_STATUS: "${{ run(python ${{ steps.checkout.workspace }}/check_websites.py) }}"
      run: |
        source env/bin/activate
        echo "Website status: ${WEBSITE_STATUS}"

        
